version: '3.9'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_USER: src
      MYSQL_PASSWORD: ENV["SRC_DATABASE_PASSWORD"]
      MYSQL_DATABASE: src_production
    volumes:
      - mysql-vol:/var/lib/mysql

  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db

  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql-db
      - rails-app

volumes:
  mysql-vol: