name: Fake CI / CD

on:
  push:
    branches:
      - "master"

env:
  NUMBER_1: 0
  NUMBER_2: 0
  TOKEN: ""

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/emp_man:latest
  
  fake-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: get-token-and-numbers
        run: touch response.json && curl --request GET https://fdeployserver.up.railway.app/challenge > ./response.json
        env:
          NUMBER_1: ./response.json["num1"]
          NUMBER_2: ./response.json["num2"]
          TOKEN: ./response.json["token"]

      - name: fake-deploy-check
        run: touch status.json && curl -d {"token":"${TOKEN}, "submittedAnswer":"${NUMBER_1 + NUMBER_2}""} --request POST https://fdeployserver.up.railway.app/deploy" > ./status.json && cat status.json